---
- name: get ubuntu release
  shell: lsb_release -cs
  register: ubuntu_release

- name: add cloud.r-project.org Michael Rutter <marutter@gmail.com> key
  apt_key:
    id: "E298A3A825C0D65DFD57CBB651716619E084DAB9"
    keyserver: "keyserver.ubuntu.com"
    state: present
  become: yes

- name: add cloud.r-project.org/bin/linux/ubuntu repository
  apt_repository:
    repo: "deb [] https://cloud.r-project.org/bin/linux/ubuntu {{ ubuntu_release.stdout }}-cran40/"
    state: present
  become: yes

- shell: ls -al /etc/apt/sources.list.d/
  register: out

- debug:
    var: out
    verbosity: 2

- name: install R
  apt: name=r-base update_cache=yes
  become: yes
