- name: set pinned apps on the dock
  shell: >
    gsettings set org.gnome.shell favorite-apps "[
      'google-chrome.desktop',
      'org.gnome.Nautilus.desktop',
      'Zoom.desktop',
      'anki.desktop',
      'obsidian.desktop',
      'microsoft-edge.desktop',
      'code_code.desktop',
      'spotify_spotify.desktop',
      'okular_okular.desktop',
      'zotero.desktop',
      'org.gnome.Settings.desktop'
    ]"
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: Set Dock position to bottom
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: enable autohide for ubuntu dock (dash-to-dock)
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: enable auto-hide for ubuntu dock (dash-to-dock)
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: Set auto-hide delay (optional, for faster hide)
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock hide-delay 0.1
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: enable panel mode (non-extended dock height)
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"

- name: enable dark mode (gnome color-scheme)
  shell: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  environment:
    DISPLAY: ":0"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
  become_user: "{{ ansible_user_id }}"
