---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: localhost
  roles:
    - { role: base, tags: [ "base" ] }
    - { role: docker, tags: [ "docker" ] }
    - { role: fzf, tags: [ "fzf" ] }
    - { role: intellij-ce, tags: [ "intellij-ce" ] }
    - { role: awsvpn, tags: [ "awsvpn" ] }
    - { role: java-developer, tags: [ "java-developer" ] }
    - { role: node, tags: [ "node" ] }
    - { role: nvim, tags: [ "nvim" ] }
    - { role: tmux, tags: [ "tmux" ] }
    - { role: zsh, tags: [ "zsh" ] }
