---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: localhost
  roles:
    - { role: base, tags: [ "base" ] }
    - { role: docker, tags: [ "docker" ] }
    - { role: fzf, tags: [ "fzf" ] }
    - { role: intellij_ce, tags: [ "intellij_ce" ] }
    - { role: aws_vpn, tags: [ "aws_vpn" ] }
    - { role: java_developer, tags: [ "java_developer" ] }
    - { role: javascript_developer, tags: [ "node_developer" ] }
    - { role: nvim, tags: [ "nvim" ] }
    - { role: tmux, tags: [ "tmux" ] }
    - { role: zsh, tags: [ "zsh" ] }
