---
- hosts: localhost
  roles:
    - { role: nvim, tags: [ "nvim" ] }
    - { role: python, tags: [ "python" ] }
    - { role: zotero, tags: [ "zotero" ] }
    - { role: last, tags: [ "last" ] }
    - { role: citrix, tags: [ "citrix" ] }
