---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: localhost
  vars:
    preferred_shell: zsh
    intellij_ce_vim: true
  roles:
    - { role: base, tags: [ "base" ] }
    - { role: aws_developer, tags: [ "aws_developer" ] }
    - { role: dbeaver, tags: [ "dbeaver" ] }
    - { role: docker, tags: [ "docker" ] }
    - { role: fzf, tags: [ "fzf" ] }
    - { role: tmux, tags: [ "tmux" ] }
    - { role: intellij_ce, tags: [ "intellij_ce" ] }
    - { role: java_developer, tags: [ "java_developer" ] }
    - { role: javascript_developer, tags: [ "javascript_developer" ] }
    - { role: python_developer, tags: [ "python_developer" ] }
    - { role: spotify, tags: [ "spotify" ] }
    - { role: nvim, tags: [ "nvim" ] }
    - { role: zsh, tags: [ "zsh" ] }
    - { role: kubernetes_developer, tags: [ "kubernetes_developer" ] }
