---
- hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: all
  roles:
    - base
    - docker
    - fzf
    - iterm2
    - node
    - nvim
    - tmux
    - zsh
