---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

    - name: debug
      ansible.builtin.debug:
        var: ansible_facts

# base
- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: os_Ubuntu
  roles:
    - base

# common
- hosts: localhost
  roles:
    - zsh
    - nvim
    - vscode
    - fzf
    - tmux
    - { role: docker, tags: [ "extra" ] }
    - { role: pia, tags: [ "extra" ] }
    - { role: lastpass, tags: [ "extra" ] }

# extra
- hosts: os_MacOSX
  roles:
    - { role: iterm2, tags: [ "extra" ] }

- hosts: os_Ubuntu
  roles:
    - { role: microk8s, tags: [ "extra" ] }