---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

    - name: debug
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 2

# base
- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: os_Ubuntu
  roles:
    - base

# common
- hosts: localhost
  vars_prompt:
    - name: github_username
      prompt: "Github username"
      private: no
    - name: github_password
      prompt: "Github password"
  roles:
    - zsh
    - nvim
    - vscode
    - fzf
    - tmux
    - docker
    - lastpass
    # - pia
    - github

# extra
- hosts: os_MacOSX
  roles:
    - iterm2

- hosts: os_Ubuntu
  roles:
    - microk8s