---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

    - name: debug
      ansible.builtin.debug:
        var: ansible_facts

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew
    - iterm2

- hosts: os_Ubuntu
  roles:
    - { role: microk8s, tags: [ "extra" ] }

- hosts: localhost
  roles:
    - base
    - zsh
    - nvim
    - vscode
    - fzf
    - tmux
    - { role: docker, tags: [ "extra" ] }
    - { role: pia, tags: [ "extra" ] }
    - { role: lastpass, tags: [ "extra" ] }