---
- hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_MacOSX
  roles:
    - geerlingguy.homebrew

- hosts: localhost
  vars:
    preferred_shell: zsh
    intellij_ce_vim: true
  roles:
    - base
    - zsh
    - tmux
    - nvim
    - fzf
    # - docker
    - virtualbox
    - java
    - javascript
    - python
