---
- name: install openvpn and Gnome GUI dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - network-manager-openvpn-gnome
    - python2.7
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Send PIA installer
  get_url:
    url: https://www.privateinternetaccess.com/installer/pia-nm.sh
    dest: /tmp/pia-nm.sh
    mode: 0700
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Execute PIA installer
  expect:
    echo: yes
    command: /tmp/pia-nm.sh
    responses:
      (.*)PIA username(.*): "{{ pia_username }}"
      (.*)Connection method(.*): "{{ pia_conn_method }}"
      (.*)Strong encryption(.*): "{{ pia_strong_encryption }}"
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Remove the zsh-installer.sh
  file: path=/tmp/pia-nm.sh state=absent
  when: ansible_distribution == "Ubuntu"
  become: yes
