---
- name: install zotero prerequisites
  ansible.builtin.apt: name=libdbus-glib-1-2 update_cache=true
  become: true

- name: get latest zotero release tag from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/zotero/zotero/tags
    headers:
      Accept: application/vnd.github.v3+json
    return_content: true
  register: uri_res

- name: debug zotero release tag
  debug: var=uri_res.json[0].name verbosity=2

- name: download zotero release tarball
  ansible.builtin.uri:
    url: "https://download.zotero.org/client/release/{{ uri_res.json[0].name }}/Zotero-{{ uri_res.json[0].name }}_linux-x86_64.tar.bz2"
    headers:
      Accept: application/vnd.github.v3+json
    dest: "/tmp/Zotero-{{ uri_res.json[0].name }}_linux-x86_64.tar.bz2"
    creates: "/tmp/Zotero-{{ uri_res.json[0].name }}_linux-x86_64.tar.bz2"
    status_code: [200, 304]

- name: unarchive zotero tarball to /opt
  ansible.builtin.unarchive:
    src: "/tmp/Zotero-{{ uri_res.json[0].name }}_linux-x86_64.tar.bz2"
    dest: /opt
  become: true

- name: set zotero launcher icon
  ansible.builtin.command: /opt/Zotero_linux-x86_64/set_launcher_icon

- name: link zotero desktop file to local applications
  ansible.builtin.file:
    src: /opt/Zotero_linux-x86_64/zotero.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/zotero.desktop"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    state: link

- name: link .zotero config directory
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/Insync/michael.w.baroody@gmail.com/Google\ Drive/zotero"
    dest: "{{ ansible_env.HOME }}/.zotero"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    state: link
    force: true
