---
- name: install iptables
  apt: name=iptables update_cache=yes

- name: create /etc/iptables/
  file: path=/etc/iptables state=directory mode=0755

- name: copy pia killswitch configuration
  copy: 
    src: pia_killswitch.rules
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: 0644
  when: vpn_provider == 'pia'
  notify:
    - restart iptables

# https://help.ubuntu.com/community/IptablesHowTo#Configuration_on_startup

# the following starts iptables before the interface
# comes up for maximum security
- name: iptablesload script on network pre-up 
  copy:
    src: iptablesload.sh
    dest: /etc/network/if-pre-up.d/
    owner: root
    group: root
    mode: 0744

# simple script that save any iptables changes after interface
# comes down
- name: iptablessave script on network post-down
  copy:
    src: iptablessave.sh
    dest: /etc/network/if-post-down.d/
    owner: root
    group: root
    mode: 0744

- name: enable filter table kernel module
  command: modprobe iptable_filter
