---
- ansible.builtin.apt: name=python3-venv

- ansible.builtin.pip: name=openai-whisper

- name: download pyenv installer
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv-installer.sh
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0500
  become: true

- name: run pyenv installer
  ansible.builtin.shell: /tmp/pyenv-installer.sh
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/"

- name: configure shell (zsh only)
  ansible.builtin.copy:
    src: files/pyenv.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/pyenv.zsh"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0644