---
- name: install zsh (macos)
  homebrew: name=zsh state=present update_homebrew=yes
  when: ansible_distribution == "MacOSX"

- name: install zsh (ubuntu)
  apt: name=zsh update_cache=yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: change default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    clone: yes
    depth: 1
    accept_hostkey: true
    force: yes # squashes any changes

- name: install .zshrc
  copy:
    src: files/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644

- name: install .zsh_history
  ansible.builtin.file:
    src: "/home/{{ ansible_user_id }}/Insync/michael.w.baroody@gmail.com/Google Drive/zsh_history"
    dest: "/home/{{ ansible_user_id }}/.zsh_history"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    state: link

## add miscellaneous custom scripts
- name: copy pdfutils plugin
  ansible.builtin.copy:
    src: files/plugins/pdfutils
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0644

- name: copy meetingtranscription plugin
  ansible.builtin.copy:
    src: files/plugins/meetingtranscription
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0644