---
- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1

- name: run fzf install script
  command: "{{ ansible_env.HOME }}/.fzf/install --no-fish"
