---
- name: generate ssh key for git
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/git_id_rsa"
    comment: "{{ git_email }}"
    type: rsa
    size: 4096
    mode: 0600
  register: keypair

- name: add ssh key to git
  uri:
    url: https://api.github.com/user/keys
    method: POST
    url_username: "{{ git_username }}"
    url_password: "{{ git_password }}"
    headers:
      Accept: application/vnd.github.v3+json
    body_format: json
    body:
      title: "{{ git_ssh_key_title }}"
      key: "{{ keypair.public_key }}"
    status_code: [ 201, 422 ]
    force_basic_auth: yes
  register: uri_res

- debug: var=uri_res verbosity=2
