# -*- coding: utf-8 -*-
#
# AMBOSS add-on Add-on for Anki
# Copyright (C)  2024 amboss-mededu
#
# This file was automatically generated by Anki Add-on Builder v1.0.0-dev.5
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "navbar",
    "settings",
    "sidepanel"
]

from . import navbar
from . import settings
from . import sidepanel
