- name: install vim-gtk
  apt: name=vim-gtk update_cache=yes
  become: yes

- name: install dotfiles
  synchronize:
    src: files/
    dest: "{{ ansible_env.HOME}}/.vim/"
    owner: yes
    group: yes

- name: install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME}}/.vim/bundle/Vundle.vim"
    accept_hostkey: true

- name: install Vundle plugins
  command: vim -E -s -c "source {{ ansible_env.HOME}}/.vim/vimrc" +PluginInstall +qall
