---
- name: mkdir /tmp/sdkman
  ansible.builtin.file:
    path: /tmp/sdkman
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0555
  become: true

- name: download sdkman installer
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman/sdkman-installer.sh
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0555
  become: true

- name: run sdkman installer
  ansible.builtin.shell: /tmp/sdkman/sdkman-installer.sh

- name: configure shell (zsh only)
  ansible.builtin.copy:
    src: files/sdkman.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/sdkman.zsh"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0644

# https://sdkman.io/usage
- name: set commonsense sdkman configs
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.sdkman/etc/config"
    regexp: "sdkman_auto_env=.*"
    line: "sdkman_auto_env=true"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0444
