---
- name: install tmux
  homebrew: name=tmux state=present update_homebrew=yes
  when: ansible_distribution == "MacOSX"

- name: install tmux
  apt: name=tmux update_cache=yes
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: install tmux.conf
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    mode: 0644

- name: install tpm plugins
  shell: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/scripts/install_plugins.sh"
