- name: install tmux
  apt: name=tmux update_cache=yes
  become: yes

- name: install tmux.conf
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
