---
- name: install docker (macos)
  homebrew_cask:
    name: docker
    state: present
    update_homebrew: yes
  when: ansible_distribution == "MacOSX"

- name: install docker (ubuntu)
  community.general.snap:
    name: docker
    state: present
  become: yes
  when: ansible_facts["os_family"] == "Debian" or ansible_facts["os_family"] == "RedHat"
