---
# mostly based on the following guide: https://docs.docker.com/engine/install/ubuntu
# WARNING: although tempting, don't try and use snap to install docker (https://github.com/docker/machine/issues/4590#issuecomment-797161961, among other issues)

- name: dpkg --print-architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: architecture_response
  when: ansible_facts["os_family"] == "Debian"

- name: install docker (macos)
  homebrew_cask:
    name: docker
    state: present
    update_homebrew: yes
  when: ansible_distribution == "MacOSX"

- name: install pre-reqs
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: download docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: 0444
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: add docker gpg key
  ansible.builtin.shell: cat /tmp/docker.gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: add apt repository
  ansible.builtin.template:
    src: templates/docker.list
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0444
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: install pre-reqs
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: add docker group
  ansible.builtin.shell: groupadd --force docker
  become: yes
  when: ansible_facts["os_family"] == "Debian"

- name: add docker group to user groups
  ansible.builtin.shell: usermod -aG docker "{{ ansible_env.USER }}"
  become: yes
  when: ansible_facts["os_family"] == "Debian"
