---
####  ubuntu #####
- name: update/upgrade system
  apt:
    update_cache: yes
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: install build tools
  apt:
    name:
    - build-essential
    - gcc
    update_cache: yes
  become: yes
  when: ansible_distribution == "Ubuntu"