---
- name: update/upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  become: true
  when: ansible_distribution == "Ubuntu"

- name: install useful packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
      # - insync
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- community.general.snap:
    name:
      - nordvpn
      - postman
      - dbeaver-ce
      - spotify
      - pdftk
      - k9s
      - docker
  become: true
  when: ansible_distribution == "Ubuntu"

- name: add docker group
  ansible.builtin.shell: groupadd --force docker
  become: true
  when: ansible_facts["os_family"] == "Debian"

- name: add docker group to user groups
  ansible.builtin.shell: usermod -aG docker "{{ ansible_env.USER }}"
  become: true
  when: ansible_facts["os_family"] == "Debian"

- community.general.snap:
    name:
      - code
      - obsidian
    classic: true
  become: true
  when: ansible_distribution == "Ubuntu"