---
- name: install required/useful apt packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
      - xclip
      - htop
      - pulseaudio
    update_cache: true
  become: true

- name: install base snaps
  community.general.snap:
    name:
      - nordvpn
      - postman
      - dbeaver-ce
      - spotify
      - pdftk
      - docker
      - ffmpeg
      - okular
      - transmission
      - vlc
      - gnome-calendar
      - libreoffice
      - gimp
  become: true

- name: install vscode snap
  community.general.snap:
    name: code
    classic: true
  become: true

- name: install google chrome deb
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- name: install zoom deb
  ansible.builtin.apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
  become: true

- name: install warp
  ansible.builtin.apt:
    deb: https://app.warp.dev/download?package=deb
  become: true

- name: upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  become: true

- name: generate an openssh keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    type: ed25519
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    comment: michael.w.baroody@gmail.com

- name: add docker group
  ansible.builtin.shell: groupadd --force docker
  become: true

- name: add user to docker group
  ansible.builtin.shell: usermod -aG docker "{{ ansible_env.USER }}"
  become: true
