---
- name: update/upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: install useful packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - pdftk
    update_cache: yes
  become: yes
  when: ansible_distribution == "Ubuntu"
