---
- name: update/upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  become: true
  when: ansible_distribution == "Ubuntu"

- name: install useful packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
      # - insync
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: install snaps
  community.general.snap:
    name:
      - nordvpn
      - code
      - postman
      - dbeaver-ce
      - spotify
      - pdftk
      - obsidian
      - k9s
  when: ansible_distribution == "Ubuntu"
