---
- name: update/upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  become: true

- name: install useful packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
    update_cache: true
  become: true

- community.general.snap:
    name:
      - nordvpn
      - postman
      - dbeaver-ce
      - spotify
      - pdftk
      - docker
      - code
      # - insync
      # - obsidian
  become: true

- name: Install Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


# - name: add docker group
#   ansible.builtin.shell: groupadd --force docker
#   become: true
#   when: ansible_distribution == "Ubuntu"

# - name: add docker group to user groups
#   ansible.builtin.shell: usermod -aG docker "{{ ansible_env.USER }}"
#   become: true
#   when: ansible_distribution == "Ubuntu"