---
- ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  become: true

- ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - curl
    update_cache: true
  become: true

- community.general.snap:
    name:
      - nordvpn
      - postman
      - dbeaver-ce
      - spotify
      - pdftk
      - docker
      # - insync
      # - obsidian
  become: true

- community.general.snap:
    name: code
    classic: true
  become: true

- ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- ansible.builtin.apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
  become: true

- name: add docker group
  ansible.builtin.shell: groupadd --force docker
  become: true

- name: add docker group to user groups
  ansible.builtin.shell: usermod -aG docker "{{ ansible_env.USER }}"
  become: true