- name: install macvim
  homebrew: name=macvim state=present update_homebrew=yes

- name: install dotfiles
  synchronize:
    src: files/
    dest: "{{ ansible_env.HOME}}/.vim/"
    owner: yes
    group: yes

- name: install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME}}/.vim/bundle/Vundle.vim"
    accept_hostkey: true

- name: install Vundle plugins
  command: mvim -E -s -f -c "source {{ ansible_env.HOME}}/.vim/vimrc" -c "PluginInstall" -c "qall"

- name: install YouCompleteMe
  command: "./install.py"
  args:
    chdir: "{{ ansible_env.HOME }}/.vim/bundle/YouCompleteMe"
