---
##########################################################
# install vim + plugin hosts
##########################################################
- name: install nvim (MacOS)
  homebrew: name=neovim state=present update_homebrew=yes
  when: ansible_distribution == "MacOSX"

- name: install nvim (Ubuntu)
  apt: name=neovim state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: install python client/plugin host
  pip: name=pynvim state=present extra_args=--user
  when: ansible_distribution == "Ubuntu"

# TODO: make this user npm install
- name: install nodejs client/plugin host
  npm: name=neovim global=yes
  become: yes

- name: synchronize dotfiles
  synchronize:
    src: files/
    dest: "{{ ansible_env.HOME}}/.config/nvim/"
    owner: yes
    group: yes

##########################################################
# Install plugin manager + plugin dependencies
##########################################################
- name: install Plug
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"

- name: install jedi for python completion
  pip: name=jedi state=present extra_args=--user

- name: install plugins
  command: nvim -c "source {{ ansible_env.HOME }}/.config/nvim/init.vim" -c "PlugInstall" -c "qall"
