---
##########################################################
# install vim + plugin hosts
##########################################################
- community.general.snap: name=neovim
  become: true

- name: mkdir "{{ ansible_env.HOME}}/.config/nvim/"
  file:
    name: "{{ ansible_env.HOME}}/.config/nvim/"
    state: directory

- name: synchronize dotfiles
  ansible.posix.synchronize:
    src: files/
    dest: "{{ ansible_env.HOME}}/.config/nvim/"
    owner: yes
    group: yes

##########################################################
# Install plugin manager + plugin dependencies
##########################################################
- name: create autoload dir
  file: path="{{ ansible_env.HOME }}/.config/nvim/autoload" state=directory

- name: install Plug
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"

# - name: install jedi for python completion
# pip: name=jedi state=present extra_args=--user

- name: install plugins
  command: >
    nvim
      -c "source {{ ansible_env.HOME }}/.config/nvim/init.vim" \
      -c "PlugInstall" \
      -c "CocInstall -sync" \
      -c "qall"

- name: install ripgrep for fuzzy searching files
  community.general.snap: name=ripgrep classic=true
  become: true

- name: configure shell (zsh only)
  ansible.builtin.copy:
    src: files/nvim.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/nvim.zsh"
    owner: "{{ ansible_user_id | string }}"
    group: "{{ ansible_user_gid | string }}"
    mode: 0644
