---
##########################################################
# install vim + plugin hosts
##########################################################
- name: install nvim snap
  community.general.snap:
    name: nvim
    classic: true
  become: true

- name: create nvim config directory
  file:
    name: "{{ ansible_env.HOME}}/.config/nvim/"
    state: directory

- name: synchronize nvim dotfiles
  ansible.posix.synchronize:
    src: files/
    dest: "{{ ansible_env.HOME}}/.config/nvim/"
    owner: yes
    group: yes

##########################################################
# Install plugin manager + plugin dependencies
##########################################################
- name: create autoload dir
  file: path="{{ ansible_env.HOME }}/.config/nvim/autoload" state=directory

- name: install vim-plug
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"

# - name: install jedi for python completion
# pip: name=jedi state=present extra_args=--user

- name: install nvim plugins
  command: >
    nvim
      -c "source {{ ansible_env.HOME }}/.config/nvim/init.vim" \
      -c "PlugInstall" \
      -c "CocInstall -sync" \
      -c "qall"

- name: install ripgrep snap
  community.general.snap: name=ripgrep classic=true
  become: true